services:
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Development port
      - "3000:3000"  # Production port
    environment:
      - NODE_ENV=development
      - VITE_BASE_PATH=/shopper
    command: npm run start

  core:
    build:
      context: ./core
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_MAPS_API_KEY=AIzaSyAjCRzc5Pfl1Tm2ieto76tV-6f5Bx_BK5s
      - CORS_ALLOW_ORIGINS=http://localhost:5173,http://localhost:3000
      - CORS_ALLOW_METHODS=GET,POST,PUT,PATCH,DELETE,OPTIONS
      - CORS_ALLOW_HEADERS=Origin,Content-Type,Accept,Authorization
      - PLACE_SEARCH_RESULT_LIMIT=20
      - PLACE_INCLUDED_TYPES=supermarket,department_store
      - JWT_SECRET=my-secret-key
      - AI_SHOPPER_CORE_DB_HOST=userdb
      - AI_SHOPPER_CORE_DB_PORT=3306
      - AI_SHOPPER_CORE_DB_NAME=ai_shopper_core
      - AI_SHOPPER_CORE_DB_USER=ai_shopper_dev
      - AI_SHOPPER_CORE_DB_PASSWORD=password
      - AI_SHOPPER_CORE_DB_MAX_OPEN_CONNS=25
      - AI_SHOPPER_CORE_DB_MAX_IDLE_CONNS=10
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - GIN_MODE=release
      - SERVICE_NAME=core
      - LOG_LEVEL=debug

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "9096:9096"
    environment:
      - USER_DB_HOST=userdb
      - USER_DB_PORT=3306
      - USER_DB_NAME=ai_shopper_auth
      - USER_DB_USER=ai_shopper_dev
      - USER_DB_PASSWORD=password
      - CORS_ALLOW_ORIGINS=http://localhost:5173,http://localhost:3000
      - CORS_ALLOW_METHODS=GET,POST,PUT,PATCH,DELETE,OPTIONS
      - CORS_ALLOW_HEADERS=Origin,Content-Type,Accept,Authorization
      - JWT_SECRET=my-secret-key
      - IS_LOCAL_DEV=true
      - DEFAULT_USER_IDS=<<list of uuids without hyphens, seperated by comma>>
      - DEFAULT_USER_EMAILS=<<list of emails, seperated by comma>>
      - DEFAULT_PASSWORDS=<<list of passwords, bcrypt hashed, seperated by comma. Remember to escape the dollar sign>>
      - DEFAULT_CLIENT_ID=82ce1a881b304775ad288e57e41387f3
      - DEFAULT_CLIENT_SECRET=my_secret
      - DEFAULT_CLIENT_DOMAIN=http://localhost:3000
      - DEFAULT_IS_PUBLIC=1
      - DEFAULT_DESCRIPTION=Default client for shopper app
      - SERVICE_NAME=auth
      - LOG_LEVEL=trace
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USER=default
      - REDIS_PASSWORD=password
      - MAX_NUM_KEYS=5

  scraper:
    build: 
      context: ./scraper
      dockerfile: Dockerfile
    environment:
      ES_NODE: http://elasticsearch:9200
      PORT: 4000
      LOG_LEVEL: debug
    ports:
      - "4000:4000"
