services:
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Development port
      - "3000:3000"  # Production port
    environment:
      - NODE_ENV=development
    command: npm run start

  core:
    build:
      context: ./core
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_MAPS_API_KEY=AIzaSyAjCRzc5Pfl1Tm2ieto76tV-6f5Bx_BK5s
      - CORS_ALLOW_ORIGINS=http://localhost:5173,http://localhost:3000
      - CORS_ALLOW_METHODS=GET,POST,PUT,PATCH,DELETE,OPTIONS
      - CORS_ALLOW_HEADERS=Origin,Content-Type,Accept,Authorization

  # oauth2:
  #   build:
  #     context: ./oauth
  #     dockerfile: Dockerfile
  #   ports:
  #     - "9096:9096"
  #   environment:
  #     - USER_DB_HOST=userdb
  #     - USER_DB_PORT=3306
  #     - USER_DB_NAME=oauth2
  #     - USER_DB_USER=ai_shopper_dev
  #     - USER_DB_PASSWORD=password
      
