services: 
  testdb:
    image: mysql:8.0
    ports:
      - "4306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=ai_shopper_dev
      - MYSQL_PASSWORD=password

  testredis:
    image: redis:7.0
    ports:
      - "7379:6379"
    environment:
      - REDIS_ARGS=--requirepass testpassword --user default on ~* +@all\

  testelasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - action.destructive_requires_name=false # allow index deletion with wildcard, should only be used in development
    ports:
      - "10200:9200"
      - "10300:9300"



