services: 
  testdb:
    image: mysql:8.0
    ports:
      - "4306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=ai_shopper_dev
      - MYSQL_PASSWORD=password

  testredis:
    image: redis:7.0
    ports:
      - "7379:6379"
    environment:
      - REDIS_ARGS=--requirepass testpassword --user default on ~* +@all


