services:
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Development port
      - "3000:3000"  # Production port
    environment:
      - NODE_ENV=development
    command: npm run start

  core:
    build:
      context: ./core
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_MAPS_API_KEY=AIzaSyAjCRzc5Pfl1Tm2ieto76tV-6f5Bx_BK5s
      - CORS_ALLOW_ORIGINS=http://localhost:5173,http://localhost:3000
      - CORS_ALLOW_METHODS=GET,POST,PUT,PATCH,DELETE,OPTIONS
      - CORS_ALLOW_HEADERS=Origin,Content-Type,Accept,Authorization
      - PLACE_SEARCH_RESULT_LIMIT=20
      - PLACE_INCLUDED_TYPES=supermarket,department_store
      - JWT_SECRET=my-secret-key
      - AI_SHOPPER_CORE_DB_HOST=userdb
      - AI_SHOPPER_CORE_DB_PORT=3306
      - AI_SHOPPER_CORE_DB_NAME=ai_shopper_core
      - AI_SHOPPER_CORE_DB_USER=ai_shopper_dev
      - AI_SHOPPER_CORE_DB_PASSWORD=password
      - AI_SHOPPER_CORE_DB_MAX_OPEN_CONNS=25
      - AI_SHOPPER_CORE_DB_MAX_IDLE_CONNS=10
      - GIN_MODE=release
      - SERVICE_NAME=core
      - LOG_LEVEL=debug

  # service:
  #   build:
  #     context: ./service
  #     dockerfile: Dockerfile
  #   environment:
  #     - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "9096:9096"
    environment:
      - USER_DB_HOST=userdb
      - USER_DB_PORT=3306
      - USER_DB_NAME=ai_shopper_auth
      - USER_DB_USER=ai_shopper_dev
      - USER_DB_PASSWORD=password
      - CORS_ALLOW_ORIGINS=http://localhost:5173,http://localhost:3000
      - CORS_ALLOW_METHODS=GET,POST,PUT,PATCH,DELETE,OPTIONS
      - CORS_ALLOW_HEADERS=Origin,Content-Type,Accept,Authorization
      - JWT_SECRET=my-secret-key
      - IS_LOCAL_DEV=true
      - SERVICE_NAME=auth
      - LOG_LEVEL=debug
